### PR TITLE
Add support for Fritz!400 buttons

### LINKED ISSUE #71: Fritz!DECT 400 Support
Hi,
would it be possible to get Homebridge support for a Fritz!DECT 400 Button?

### PR DESCRIPTION
**Pull request by andig**
Fixes https://github.com/andig/homebridge-fritz/issues/71

### CODE REVIEW

**Comment by marslyric** [comment]
Hi andig,
Any news from the development?
I have now 2 additional hardware keys (400er) and could test if there is a testable software. 
What could I help in any way?
Thanks in awards

**Comment by andig** [comment]
> What could I help in any way?

You could test this PR- its waiting for you ;)

**Comment by marslyric** [comment]
Sorry, I have no glue how to implement the file I see on your branch into my homebridge.
Maybe at Xmas my son can help me. 
Sorry I am an old c programmer and has never used GitHub.
I Try to install 0.9.0:
sudo npm i homebridge-fritz@0.9.0 -g        
npm ERR! code ETARGET
npm ERR! notarget No matching version found for homebridge-fritz@0.9.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
Sorry

**Comment by andig** [comment]
> Sorry, I have no glue how to implement the file I see on your branch into my homebridge.

Ahh, kein Problem:

    npm i https://github.com/andig/homebridge-fritz#button

installiert Dir den Branch zum testen!

**Comment by andig** [comment]
Released as 0.9.2 - danke für Deine Geduld, hatte das PR-Feedback leider übersehen :(

**Pull request merged**
