### PR TITLE
Expose fritz api object

### PR DESCRIPTION
**Pull request by andig**

### CODE REVIEW

**Comment by philippehret** [comment]
It doesn't throw an error when triggering a scene and the devices are set to automatic. But it started calling the device list with all attributes for every thermostat. Because Heating state is set to automatic, it jumps back to the timetable in the FB, which I always set to cooling.

Logs for different scenarios are attached. I'm sorry in advance, should have reduced my number of thermostats for testing.

[cooling-automode.txt](https://github.com/andig/homebridge-fritz/files/2511623/cooling-automode.txt)
[cooling-coolmode.txt](https://github.com/andig/homebridge-fritz/files/2511624/cooling-coolmode.txt)
[heating-automode.txt](https://github.com/andig/homebridge-fritz/files/2511625/heating-automode.txt)
[heating-heatmode.txt](https://github.com/andig/homebridge-fritz/files/2511626/heating-heatmode.txt)
[manual-setting.txt](https://github.com/andig/homebridge-fritz/files/2511687/manual-setting.txt)

**Comment by andig** [comment]
Sounds like the expected behaviour???

**Comment by philippehret** [comment]
Error messages are fixed, but the overall problem of self resetting thermostats automation/scenes still remains. Automation/Scenes only work when HomeKit and Fritz!Box temperatures for either modes are set the same.

**Comment by andig** [comment]
> overall problem of self resetting thermostats automation/scenes still remains. Automation/Scenes only work when HomeKit and Fritz!Box temperatures for either modes are set the same.

Since I'm not using scenes I really don't know what that is supposed to mean. I'll merge this for now. Could you please provide a simple case of "desired behaviour" vs "actual behaviour" in the original issue? Or feel free to open a new one.

**Comment by philippehret** [comment]
Thanks! I try to break down the behavior in the original issue.

**Comment by andig** [comment]
Kannst Du auch gerne auf Deutsch machen- vielleicht einfacher :)

**Comment by philippehret** [comment]
> Kannst Du auch gerne auf Deutsch machen- vielleicht einfacher 😊

Jetzt habe ich schon auf Englisch angefangen  🙈

**Pull request merged**
