### PR TITLE
Change case for fritzbox to uppercase

### PR DESCRIPTION
**Pull request by BITespresso**
I suggest for better consistency to always use the uppercase for FRITZ in FRITZ!...

Therefore, I created this pull request.

Best Regards,

Michael

### CODE REVIEW

**Comment by andig** [comment]
Thank you, this seems to be the spelling that AVM prefers.

**Comment by thoschworks** [comment]
> I suggest for better consistency to always use the uppercase for FRITZ in FRITZ!...
> 
> Therefore, I created this pull request.
> 

@BITespresso Sorry that I have to say this: Thank for an idea which broke thousands of running installation without any reason.

**Comment by andig** [comment]
@thoschworks stop doing this. Nobody intended any harm and out of your thousands of installations few had to escalate via issues. I will not tolerate you harassing contributors.

**Comment by thoschworks** [comment]
@andig 

Perhaps it was not very friendly, but in my eyes it was no harassment. Definitely not one of my best moments.

I deleted the comment.

**Pull request merged**
