### PR TITLE
Add improved device configuration

### LINKED ISSUE #31: Allow selectively disabling device characteristics
The Dect200 and 210 have a temperature sensor, can be hidden it in homebridge?

### PR DESCRIPTION
**Pull request by andig**
Fixes #31, #42, #44, #60, #50, #51

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
I was just trying to update from the invert branch. I tried different configurations using the format explained in the readme (of the invert branch). In any case I got this error in the logs:

`Apr 04 10:09:11 raspberrypi homebridge[17534]: [4/4/2019, 10:09:11 AM] [FritzBox] Initializing Fritz!Box platform accessories failed - wrong user credentials?` 

The master branch works fine with my setup (Fritzbox 6490, Fritz Dect 200, raspberry pi)

**Comment by andig** [comment]
Should be fixed. There are still problems with the guest wifi config that will take a moment longer to address.

**Comment by andig** [comment]
@AaronDavidSchneider could you double-check its working now?

**Comment by AaronDavidSchneider** [comment]
It works! Thank you for the great plugin!

**Pull request merged**
